// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskAPI.Models
{
    public partial class Users
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        public string Dni { get; set; }

        public virtual Administrators Administrators { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Passwords Passwords { get; set; }
    }
}